### ISSUE TITLE
Element not interactable

### ISSUE THREAD

**Issue by alexissahagun1** [harshibar/common-intern#9]
Hi, I got an error after I setup the program with my info, I know that the error means that the element is not visible yet, but I can't find a solution to it.

`DevTools listening on ws://127.0.0.1:1862/devtools/browser/2700e967-dbdf-4d49-9164-4dd5edb873bb
Traceback (most recent call last):
  File "apply.py", line 168, in <module>
    aggregatedURLs = get_links.getURLs()
  File "C:\Users\AlexisSahagun\common-intern\get_links.py", line 137, in getURLs
    success = go_to_listings(driver)
  File "C:\Users\AlexisSahagun\common-intern\get_links.py", line 48, in go_to_listings
    location_field.clear()
  File "C:\Users\AlexisSahagun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "C:\Users\AlexisSahagun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\AlexisSahagun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AlexisSahagun\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=84.0.4147.135)`

**Comment by giosal** [comment]
Running into same problem here
```
Traceback (most recent call last):
  File ".\get_links.py", line 184, in <module>
    getURLs()
  File ".\get_links.py", line 137, in getURLs
    success = go_to_listings(driver)
  File ".\get_links.py", line 48, in go_to_listings
    location_field.clear()
  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 95, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\***\AppData\Roaming\Python\Python38\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=86.0.4240.198)
```

Disclaimer: replaced username with ***

**Comment by giosal** [comment]
Found a solution here and will ask for merge.
The driver can't find the element `sc.location` when the window is not maximized, depending on your screen resolution. If you take a look at the page, the location input field is missing. So, I propose to start window maximized to avoid this error.
Add the following code before driver initialization:
```
options = webdriver.ChromeOptions()
options.add_argument("--start-maximized")
```
on Windows or `--kiosk` on Linux
and then replace driver initialization with the following (don't forget to add the driver location if needed:
```driver = webdriver.Chrome(options=options)```

**Comment by abhijeet010304** [comment]
Solution by @giosal worked for me !! i.e you can run getlinks file by maximising the window .
